# Generated by Django 2.2.1 on 2020-06-21 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
